### ISSUE TITLE
hapi is a prerequisite

### ISSUE THREAD

**Issue by fedorov** [DeepPhe/DeepPhe-Viz#33] opened 2018-12-27 22:17 UTC
Unless `hapi` is installed, there is runtime error below starting the server. This should probably be mentioned in the documentation.

```
$ node server.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'hapi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/fedorov/github/DeepPhe-Viz/server.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by yuanzhou** [comment] 2019-01-22 16:05
Sorry @fedorov I didn't realize your issue from a few weeks back. It was the holiday break. 

To run the viz tool, you don't need to explicitly install `hapi`. It's a dependency that will be installed automatically when you install the viz tool with `npm install` command. 

What version of your Nodejs and NPM?

**Comment by yuanzhou** [comment] 2019-01-29 19:54
I verified the installation from a fresh directory and installed with `npm install`. I couldn't reproduce your issue.

**Comment by fedorov** [comment] 2019-01-29 19:57
I have node v10.14.2, and npm 6.4.1. Feel free to close - I just thought this would be helpful. I can't make time to try to reproduce the exact issue from scratch at the moment.

**Comment by yuanzhou** [comment] 2019-01-29 20:07
I have been using the same node and nom version actually. I also tested with node v10.13.0 and v10.15.1 and didn't see any installation problem. Please let me know if you see the same issue in your next installation. Thanks.

**Closed by yuanzhou** 2019-01-29 20:07 UTC
